# Site settings
title: "blog"
email: daviddd.kl@gmail.compressed
description: > # this means to ignore newlines until "baseurl:"
  daklassen &copy 2017
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  daklassen

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: rouge

# Pagination
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed

gems: [jekyll-paginate]